if (self.CavalryLogger) { CavalryLogger.start_js(["Wpno8gb"]); }

__d("PagesCometComposerDialogQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"2844694438988151",metadata:{},name:"PagesCometComposerDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PagesCometComposerDialog.entrypoint",["JSResourceForInteraction","PagesCometComposerDialogQuery$Parameters","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.id;return{queries:{dialogQueryReference:{parameters:b("PagesCometComposerDialogQuery$Parameters"),variables:{id:a,privacySelectorRenderLocation:"COMET_COMPOSER",scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("PagesCometComposerDialog.react").__setRef("PagesCometComposerDialog.entrypoint")};g["default"]=a}),98);
__d("useCometPageComposerDialog",["fbt","CometCardedDialog.react","FeedComposerCometGlimmer.react","PagesCometComposerDialog.entrypoint","emptyFunction","react","useCometEntryPointDialog"],(function(a,b,c,d,e,f,g,h){"use strict";var i=d("react"),j=d("react").useCallback,k={withCloseButton:!0};function l(a){return i.jsx("div",{children:i.jsx(c("CometCardedDialog.react"),babelHelpers["extends"]({size:"content",title:a.title},a,{children:i.jsx(c("FeedComposerCometGlimmer.react"),{})}))})}l.displayName=l.name+" [from "+f.id+"]";function a(a){var b=a.actorID,d=a.composerEntryPointRef,e=a.composerType,f=a.onBeforeClose,g=a.onSave,m=a.pageID,n=a.title,o=n===void 0?h._("T\u1ea1o b\u00e0i vi\u1ebft"):n,p=(n=a.onClose)!=null?n:c("emptyFunction");a=c("useCometEntryPointDialog")(c("PagesCometComposerDialog.entrypoint"),{id:m},void 0,function(){return i.jsx(l,babelHelpers["extends"]({title:o},k))});var q=a[0];n=a[1];a=a[2];return[j(function(a){a=a||{};var c=a.beginningViewState;a=a.pushedPageOnLoad;q(babelHelpers["extends"]({actorID:b,beginningViewState:c,composerEntryPointRef:d,composerType:e,onBeforeClose:f,onClose:p,onSave:g,pageID:m,pushedPageOnLoad:a,title:o},k),p)},[b,d,e,f,p,g,m,q,o]),n,a]}g["default"]=a}),98);
__d("PageBookmarkLaunchpointLoggerUtils",["react","requireDeferred","useSinglePartialViewImpression"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useCallback,i=c("requireDeferred")("PagesPageBookmarkLaunchpointImpressionFalcoEvent").__setRef("PageBookmarkLaunchpointLoggerUtils");function a(a){var b=h(function(){i.onReady(function(b){return b.log(function(){return{event_data:{tab:a},event_location:"launchpoint_content"}})})},[a]);return c("useSinglePartialViewImpression")({onImpressionStart:b})}g.usePageBookmarkLaunchpointImpressionLogger=a}),98);
__d("XBizSuiteControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/latest/{?*rest}",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("XCometPageVanityControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/{vanity}/",Object.freeze({ref:""}),void 0);b=a;g["default"]=b}),98);
__d("XCometPageVanityNotificationsControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/{vanity}/notifications/",Object.freeze({ref:""}),void 0);b=a;g["default"]=b}),98);
__d("XMediaManagerControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/creatorstudio/{?*tab_route}/",Object.freeze({override_mweb_check:!1,open_bulk_upload_panel:!1,mta_onboarding_includes_brand_collabs:!1,mta_onboarding_deferred_payout:!1,open_videolist_creation_dialogue:!1,open_basic_post_composer:!1,open_igtv_uploader:!1,open_boost_post_dialog:!1,open_promo_dialog:!1,show_live_break_custom_video_tray:!1}),void 0);b=a;g["default"]=b}),98);